/* O dicionário da Academia: só o inglês. A chave é o português, tal como está
 no código (t("…")) ou na base (textos de origem). Uma chave que mude no
 código perde a tradução em silêncio — o teste 15-idioma.mjs apanha-o. */
const EN = {
  ", a {n} aulas por semana": ", at {n} lessons a week",
  "/mês": "/month",
  "1 aula": "1 lesson",
  "1 avaliação": "1 rating",
  "1 conteúdo": "1 item",
  "1 dia seguido": "1 day in a row",
  "1 módulo": "1 module",
  "5 dias seguidos de estudo.": "5 days of study in a row.",
  "A abrir o evento na sua agenda...": "Opening the event in your calendar...",
  "A abrir o seu convite...": "Opening your invitation...",
  "A anunciar": "To be announced",
  "A carregar os seus cursos...": "Loading your courses...",
  "A entrar...": "Signing in...",
  "A língua em que vê a Academia. O conteúdo dos cursos fica como foi escrito.": "The language you see the Academy in. Course content stays as it was written.",
  "A nova password deve ter pelo menos 6 caracteres": "The new password must be at least 6 characters",
  "A password tem de ter pelo menos 8 caracteres.": "The password must be at least 8 characters.",
  "A preparar a sua área de membros...": "Getting your members area ready...",
  "A sua conta ainda não está ligada à academia. Fale com a mentoria.": "Your account isn't linked to the Academy yet. Talk to your mentor.",
  "A sua password": "Your password",
  "A sua presença": "Your attendance",
  "A sua trilha": "Your path",
  "Abrir menu": "Open menu",
  "Abrir o curso": "Open the course",
  "Aceda à sua área de membros e continue os seus cursos onde ficou — módulos, aulas, comunidade e o seu progresso, tudo num só lugar.": "Sign in to your members area and pick up your courses where you left off — modules, lessons, community and your progress, all in one place.",
  "Acesso": "Access",
  "agora": "now",
  "Ainda não houve encontros.": "There haven't been any sessions yet.",
  "Ainda não há cursos com certificado.": "There are no courses with a certificate yet.",
  "Ainda não há cursos no seu acesso. Fale com a sua mentoria.": "There are no courses in your access yet. Talk to your mentor.",
  "Ainda não há grupos para os seus programas. Quando houver, aparecem aqui.": "There are no groups for your programmes yet. When there are, they will appear here.",
  "Ainda não tem acesso a este curso.": "You don't have access to this course yet.",
  "Ainda não tem conta? A entrada é por convite —": "Don't have an account yet? Access is by invitation —",
  "Ainda não tem nenhum curso aberto. Assim que a mentoria lhe der acesso, aparece aqui.": "You don't have any open courses yet. As soon as your mentor gives you access, it will appear here.",
  "Ainda não tem nenhum curso disponível. Assim que a sua mentoria libertar o acesso, ele aparece aqui.": "You don't have any courses yet. As soon as your mentor gives you access, it will appear here.",
  "Ajuda-nos a perceber por onde entrar.": "It helps us understand where to start.",
  "Algo correu mal ao abrir a área de membros": "Something went wrong opening the members area",
  "Alterar foto": "Change photo",
  "Alterações guardadas com sucesso": "Changes saved",
  "Alternar tema": "Switch theme",
  "amanhã": "tomorrow",
  "As aulas abrem": "Lessons open",
  "As duas passwords não são iguais.": "The two passwords don't match.",
  "As passwords não coincidem": "The passwords don't match",
  "Atingiu 50% do seu progresso geral.": "You reached 50% of your overall progress.",
  "Atividade da comunidade": "Community activity",
  "Aula anterior": "Previous lesson",
  "Aula concluída": "Lesson completed",
  "Aulas concluídas": "Lessons completed",
  "Autoridade constrói-se em privado, muito antes de aparecer em público.": "Authority is built in private, long before it shows in public.",
  "Avaliação": "Rating",
  "Avaliação enviada. Aparece assim que a mentoria a aprovar.": "Rating sent. It will appear once your mentor approves it.",
  "Avaliação enviada. Obrigado pelo feedback!": "Rating sent. Thank you for the feedback!",
  "Avalie esta aula": "Rate this lesson",
  "Boas-vindas à academia": "Welcome to the Academy",
  "Cada aula concluída soma pontos de experiência e aproxima-o da próxima conquista.": "Every lesson you complete adds experience points and brings you closer to the next achievement.",
  "Calendário": "Calendar",
  "Cancelar": "Cancel",
  "Categorias": "Categories",
  "CERTIFICADO DE CONCLUSÃO": "CERTIFICATE OF COMPLETION",
  "Certificado gravado": "Certificate saved",
  "Certificados": "Certificates",
  "Com": "With",
  "Com {nome}": "With {nome}",
  "Começar": "Start",
  "Começar agora": "Start now",
  "Comprou na pré-venda. O curso já é seu; as aulas aparecem aqui assim que abrirem.": "You bought in the pre-sale. The course is already yours; lessons will appear here as soon as they open.",
  "Comunidade": "Community",
  "Conclua a sua primeira aula para desbloquear a primeira conquista.": "Complete your first lesson to unlock your first achievement.",
  "Concluiu a sua primeira aula.": "You completed your first lesson.",
  "concluiu com sucesso o curso": "has successfully completed the course",
  "Concluiu {curso}: o seu certificado ficou gravado": "You completed {curso}: your certificate has been saved",
  "Concluído": "Completed",
  "Confirmada": "Confirmed",
  "Confirmar nova password": "Confirm new password",
  "Confirmar presença": "Confirm attendance",
  "Confirme o email antes de entrar. Procure a mensagem que lhe enviámos.": "Confirm your email before signing in. Look for the message we sent you.",
  "Conquista em destaque": "Featured achievement",
  "Conquistas": "Achievements",
  "Conta": "Account",
  "Conteúdo": "Content",
  "Conteúdo do curso": "Course content",
  "Continuar": "Continue",
  "Continuar de onde ficou": "Pick up where you left off",
  "Continuar de onde parei": "Continue where I left off",
  "Continue a construir: aqui está o ponto em que ficou no seu percurso.": "Keep building: here is where you left off.",
  "Cursos": "Courses",
  "Cursos ativos": "Active courses",
  "Cursos concluídos": "Courses completed",
  "Código {codigo}": "Code {codigo}",
  "daqui a {n} dias": "in {n} days",
  "Definições": "Settings",
  "Deixe um comentário sobre esta aula (opcional)...": "Leave a comment about this lesson (optional)...",
  "Demasiadas tentativas. Espere um minuto e tente de novo.": "Too many attempts. Wait a minute and try again.",
  "Desbloquear": "Unlock",
  "Descarregar": "Download",
  "Desenvolvimento Pessoal": "Personal Development",
  "dia": "day",
  "dias": "days",
  "Disponível para desbloquear": "Available to unlock",
  "Duração": "Duration",
  "Em breve": "Coming soon",
  "Em breve: ajudar outros alunos na comunidade.": "Coming soon: help other students in the community.",
  "Em modo de demonstração não há emails.": "There are no emails in demo mode.",
  "Em que ponto está agora?": "Where are you right now?",
  "Email": "Email",
  "Email inválido.": "Invalid email.",
  "Email ou password errados.": "Wrong email or password.",
  "Emblemas": "Badges",
  "Emitido em {data}": "Issued on {data}",
  "Encontro": "Session",
  "Encontros anteriores": "Past sessions",
  "Entrar": "Sign in",
  "Entrar em {grupo} ({canal}, abre fora da Academia)": "Join {grupo} ({canal}, opens outside the Academy)",
  "Entrar na academia": "Enter the Academy",
  "Entrar na sala": "Join the room",
  "Entrar na sua conta": "Sign in to your account",
  "Entre 2h e 5h por semana": "Between 2h and 5h a week",
  "Enviar avaliação": "Submit rating",
  "Enviámos um link para {email}. Confirme também a pasta de spam.": "We've sent a link to {email}. Check your spam folder too.",
  "Escolha a password com que passa a entrar. Pelo menos 8 caracteres.": "Choose the password you'll sign in with. At least 8 characters.",
  "Escolha uma nova password": "Choose a new password",
  "Escolha uma ou mais áreas. É por aí que vamos começar a sua trilha.": "Choose one or more areas. That's where we'll start your path.",
  "Escreva primeiro o seu email, e depois carregue aqui.": "Type your email first, then tap here.",
  "Espiritualidade": "Spirituality",
  "Esqueceu-se da password?": "Forgot your password?",
  "Essa password aparece em fugas de dados conhecidas. Escolha outra que não use noutro sítio.": "That password appears in known data leaks. Choose another one you don't use anywhere else.",
  "Essa password não cumpre as regras da academia: {regra}.": "That password doesn't meet the Academy's rules: {regra}.",
  "Esta aula já não está disponível.": "This lesson is no longer available.",
  "Esta aula não tem vídeo": "This lesson has no video",
  "Este acesso está bloqueado. Fale com a sua mentoria.": "This access is blocked. Talk to your mentor.",
  "Este acesso está suspenso. Fale com a sua mentoria.": "This access is suspended. Talk to your mentor.",
  "Este convite expirou a {data}. Peça um novo a quem o convidou.": "This invitation expired on {data}. Ask the person who invited you for a new one.",
  "Este convite expirou. Peça um novo a quem o convidou.": "This invitation has expired. Ask the person who invited you for a new one.",
  "Este convite foi cancelado. Peça um novo a quem o convidou.": "This invitation was cancelled. Ask the person who invited you for a new one.",
  "Este convite já foi usado. Entre com o seu email e a sua password.": "This invitation has already been used. Sign in with your email and password.",
  "Este curso não foi encontrado.": "This course was not found.",
  "Este encontro já aconteceu.": "This session has already taken place.",
  "Este encontro já não está disponível, ou não é para si.": "This session is no longer available, or it isn't for you.",
  "Este link de convite não é válido. Confirme que o abriu inteiro, a partir do email.": "This invitation link isn't valid. Make sure you opened the full link from the email.",
  "Este link já foi usado ou expirou. Peça um novo.": "This link has already been used or has expired. Ask for a new one.",
  "Este link não é válido.": "This link is not valid.",
  "Este registo está ligado a outro e não pode ficar assim.": "This record is linked to another one and can't be left like this.",
  "Este tipo de ficheiro não é aceite aqui.": "This file type isn't accepted here.",
  "Estou a começar do zero": "I'm starting from scratch",
  "Exclusivo": "Exclusive",
  "Falar com a mentoria": "Talk to your mentor",
  "fale com a sua mentoria": "talk to your mentor",
  "Fale com a sua mentoria para desbloquear isto.": "Talk to your mentor to unlock this.",
  "Fale com a sua mentoria para garantir o lugar.": "Talk to your mentor to secure your place.",
  "Fale diretamente com quem acompanha o seu percurso.": "Talk directly to the person who supports your journey.",
  "Faça a gestão do seu perfil e das suas preferências de notificação.": "Manage your profile and your notification preferences.",
  "Fechar": "Close",
  "Focámos em {areas}": "We focused on {areas}",
  "Formato": "Format",
  "Formação & Mentoria": "Training & Mentoring",
  "Foto de perfil atualizada": "Profile photo updated",
  "Fundador · Kingdom Academy": "Founder · Kingdom Academy",
  "Garantir lugar": "Secure your place",
  "Garantir na pré-venda": "Secure it in the pre-sale",
  "Geral": "General",
  "Gratuito": "Free",
  "grupo|Entrar": "Join",
  "Guardar alterações": "Save changes",
  "Guardar e entrar": "Save and sign in",
  "Guardar lembrete": "Save reminder",
  "hoje": "today",
  "há {n} dias": "{n} days ago",
  "há {n} min": "{n} min ago",
  "há {n}h": "{n}h ago",
  "Inclui": "Includes",
  "Inteligência Artificial": "Artificial Intelligence",
  "Introduza os seus dados para aceder aos seus cursos.": "Enter your details to access your courses.",
  "Início": "Home",
  "Isto costuma acontecer quando ficam dados antigos guardados neste browser. Pode repor os dados de demonstração — o conteúdo volta ao estado original.": "This usually happens when old data is left in this browser. You can reset the demo data — the content goes back to its original state.",
  "Isto já não está disponível.": "This is no longer available.",
  "Isto não está disponível de momento. Veja o que há na Vitrine, ou fale com a sua mentoria.": "This isn't available at the moment. See what's in the Showcase, or talk to your mentor.",
  "Já comecei, quero consistência": "I've started, I want consistency",
  "Já existe um registo com estes dados.": "A record with these details already exists.",
  "Já pode começar.": "You can start now.",
  "Já tem acesso": "You already have access",
  "Já tem acesso a tudo o que está disponível. Bom trabalho.": "You already have access to everything available. Well done.",
  "Lembretes de aulas": "Lesson reminders",
  "Língua": "Language",
  "Língua alterada": "Language changed",
  "Mais": "More",
  "Mais de 5h por semana": "More than 5h a week",
  "Manter sessão iniciada": "Keep me signed in",
  "Marcar como concluída": "Mark as complete",
  "Marketing e Vendas": "Marketing & Sales",
  "Materiais desta aula": "Lesson materials",
  "Membro desde": "Member since",
  "Menos de 2h por semana": "Less than 2h a week",
  "Mentalidade": "Mindset",
  "Mente Multidisciplinar": "Multidisciplinary Mind",
  "Mentor da Comunidade": "Community Mentor",
  "Mentorias em grupo, masterclasses e encontros ao vivo com a Kingdom Academy.": "Group mentoring, masterclasses and live sessions with Kingdom Academy.",
  "Metade do Caminho": "Halfway There",
  "Meus cursos": "My courses",
  "Montada a partir do que respondeu": "Built from your answers",
  "Montámos um percurso com o que tem disponível": "We put together a path with what you have",
  "Muitos pedidos ao mesmo tempo. Tente novamente daqui a pouco.": "Too many requests at once. Please try again shortly.",
  "Módulo Completo": "Module Complete",
  "na Kingdom Academy": "at Kingdom Academy",
  "Nada nesta categoria de momento.": "Nothing in this category at the moment.",
  "Navegação principal": "Main navigation",
  "Negócios": "Business",
  "Nenhum curso nesta categoria ainda.": "No courses in this category yet.",
  "Nome completo": "Full name",
  "Notificações": "Notifications",
  "Notificações por email": "Email notifications",
  "Nova aula em {curso}": "New lesson in {curso}",
  "Nova conquista desbloqueada: {titulo}": "New achievement unlocked: {titulo}",
  "Nova password": "New password",
  "Novas publicações e respostas": "New posts and replies",
  "Novidades e lembretes importantes": "News and important reminders",
  "Novo curso: {curso}": "New course: {curso}",
  "Nv.{n}": "Lv.{n}",
  "Não conseguimos falar com o servidor. Verifique a sua ligação à internet e tente de novo.": "We couldn't reach the server. Check your internet connection and try again.",
  "Não ficou guardado: {motivo}": "Not saved: {motivo}",
  "Não foi possível abrir o convite agora. Tente daqui a pouco.": "We couldn't open the invitation right now. Please try again shortly.",
  "Não foi possível carregar a biblioteca do Supabase.": "The Supabase library couldn't be loaded.",
  "Não foi possível entrar.": "We couldn't sign you in.",
  "Não foi possível enviar a foto.": "The photo couldn't be uploaded.",
  "Não foi possível enviar agora. Tente daqui a pouco.": "We couldn't send it right now. Please try again shortly.",
  "Não foi possível enviar o ficheiro.": "The file couldn't be uploaded.",
  "Não foi possível guardar.": "We couldn't save it.",
  "Não foi possível ligar à academia.": "We couldn't connect to the Academy.",
  "Não tem permissão para enviar este ficheiro.": "You don't have permission to upload this file.",
  "Não tem permissão para esta operação.": "You don't have permission for this action.",
  "Nível atual": "Current level",
  "Nível {n}": "Level {n}",
  "O certificado fica gravado quando conclui {pct}% de um curso, e é seu para sempre.": "Your certificate is saved when you complete {pct}% of a course, and it's yours to keep.",
  "O conteúdo desta aula está no texto e nos materiais abaixo. Pode marcá-la como concluída ou seguir para a próxima.": "This lesson's content is in the text and materials below. You can mark it as complete or move on to the next one.",
  "O email só pode ser alterado por um administrador.": "Only an administrator can change your email.",
  "O ficheiro é grande de mais para este tipo de conteúdo.": "The file is too large for this type of content.",
  "O pagamento abre numa página segura do Payflow. Assim que for confirmado, o acesso abre-se aqui.": "Payment opens on a secure Payflow page. Once it's confirmed, access opens here.",
  "O pagamento abre numa página segura do Payflow. Assim que for confirmado, o link da sala aparece aqui.": "Payment opens on a secure Payflow page. Once it's confirmed, the room link will appear here.",
  "O pagamento abre numa página segura do Payflow; assim que for confirmado, o curso aparece em Meus cursos e as aulas vão aparecendo lá.": "Payment opens on a secure Payflow page; once it's confirmed, the course appears in My courses and lessons will show up there.",
  "O que ainda não faz parte do seu acesso. Toque num para ver como entrar.": "What isn't part of your access yet. Tap one to see how to join.",
  "O que o trouxe aqui?": "What brought you here?",
  "o-seu-email@exemplo.com": "your-email@example.com",
  "Olá, {nome}.": "Hello, {nome}.",
  "onboarding|Entrar": "Enter",
  "Onde": "Where",
  "Online": "Online",
  "ontem": "yesterday",
  "Originais": "Originals",
  "Os comentários deste curso são revistos antes de aparecerem.": "Comments on this course are reviewed before they appear.",
  "Os grupos dos seus programas. Entre para conversar com a sua turma e com a equipa.": "The groups for your programmes. Join to talk with your cohort and the team.",
  "Os seus certificados ficaram gravados": "Your certificates have been saved",
  "Os seus cursos": "Your courses",
  "Pago": "Paid",
  "Passo 3 de 3, concluído": "Step 3 of 3, done",
  "Passo {n} de 3": "Step {n} of 3",
  "Password": "Password",
  "Password atual": "Current password",
  "Password e alterações guardadas com sucesso": "Password and changes saved",
  "Pedido inválido.": "Invalid request.",
  "Pelo menos 8 caracteres": "At least 8 characters",
  "Perdemos a ligação ao enviar o ficheiro.": "We lost the connection while uploading the file.",
  "Perdemos a ligação ao servidor. Verifique a internet e recarregue a página.": "We lost the connection to the server. Check your internet and reload the page.",
  "Perfeito.": "Perfect.",
  "Perfil": "Profile",
  "Pesquisar aulas, módulos...": "Search lessons, modules...",
  "Peça o convite a quem o acompanha na academia.": "Ask the person who supports you at the Academy for an invitation.",
  "Plano": "Plan",
  "Planos": "Plans",
  "PNG ou JPG. Sem foto, ficam as suas iniciais.": "PNG or JPG. Without a photo, your initials are shown.",
  "Por aqui, {nome}.": "This way, {nome}.",
  "Por desbloquear": "Locked",
  "Precisa de ajuda?": "Need help?",
  "Preencha o email e a password.": "Enter your email and password.",
  "Presença confirmada": "Attendance confirmed",
  "Presença confirmada!": "Attendance confirmed!",
  "Primeiro Curso Concluído": "First Course Completed",
  "Primeiro Passo": "First Step",
  "Procuro estrutura, sistemas e decisão.": "I'm looking for structure, systems and clarity.",
  "Progresso": "Progress",
  "Progresso em 3 áreas de conhecimento diferentes.": "Progress in 3 different areas of knowledge.",
  "Progresso em 3 áreas diferentes.": "Progress in 3 different areas.",
  "Progresso geral": "Overall progress",
  "Pré-venda": "Pre-sale",
  "Pré-venda: as aulas abrem a {data}": "Pre-sale: lessons open on {data}",
  "Pré-venda: as aulas abrem em breve": "Pre-sale: lessons open soon",
  "Próxima aula": "Next lesson",
  "Próximo encontro ao vivo": "Next live session",
  "Próximos encontros": "Upcoming sessions",
  "Quando": "When",
  "Quanto tempo tem por semana?": "How much time do you have each week?",
  "Quero avançar depressa.": "I want to move fast.",
  "Quero bases sólidas antes de avançar.": "I want solid foundations before moving on.",
  "Quero escalar o que já tenho": "I want to scale what I already have",
  "Quero este acesso": "I want this access",
  "Realizado": "Held",
  "Recarregar": "Reload",
  "Remover": "Remove",
  "Repita a password": "Repeat the password",
  "Repor dados": "Reset data",
  "Responder ao questionário": "Answer the questionnaire",
  "Responder de novo": "Answer again",
  "Resumo da conta": "Account summary",
  "Reveja a aula e tente de novo.": "Review the lesson and try again.",
  "Rever respostas": "Review answers",
  "ritmo {ritmo}": "pace: {ritmo}",
  "Saber mais": "Learn more",
  "Sair": "Sign out",
  "Saiu da sua conta. Até à próxima aula!": "You've signed out. See you at the next lesson!",
  "Saltar por agora": "Skip for now",
  "Se acabou de pagar, o acesso abre-se assim que confirmarmos — avisamo-lo por email.": "If you've just paid, access opens as soon as we confirm it — we'll let you know by email.",
  "Segurança": "Security",
  "Sem categoria": "Uncategorised",
  "Sem descrição para este encontro.": "No description for this session.",
  "Sem encontros agendados de momento.": "No sessions scheduled at the moment.",
  "Sem eventos agendados de momento.": "No sessions scheduled at the moment.",
  "Sem notificações por agora.": "No notifications for now.",
  "Sem plano": "No plan",
  "Sequência atual": "Current streak",
  "Sequência de Fogo": "On Fire",
  "Serve para calibrar o ritmo que lhe vamos sugerir.": "It helps us set the pace we'll suggest.",
  "Sugerida para si": "Suggested for you",
  "Suporte": "Support",
  "Telegram": "Telegram",
  "Tem de ter pelo menos 8 caracteres.": "It must be at least 8 characters.",
  "Tenho alguma coisa a andar e quero organizar.": "I have something going and want to organise it.",
  "Tentar de novo": "Try again",
  "Terminou um curso do início ao fim.": "You finished a course from start to end.",
  "Terminou um módulo inteiro.": "You finished a whole module.",
  "Teste o que ficou": "Test what you've learned",
  "Todas": "All",
  "Todos": "All",
  "Todos os seus programas, mentorias e mastermind num só lugar — {pct}% de progresso geral.": "All your programmes, mentoring and mastermind in one place — {pct}% overall progress.",
  "Turma de {inicio} a {fim}.": "Cohort from {inicio} to {fim}.",
  "Um ritmo constante, com tempo para aplicar.": "A steady pace, with time to apply it.",
  "Uma alteração não chegou ao servidor — o que vê pode não estar gravado.": "A change didn't reach the server — what you see may not be saved.",
  "Uma aula de cada vez, sem pressa.": "One lesson at a time, no rush.",
  "Ver a minha trilha": "See my path",
  "Ver calendário": "View calendar",
  "Ver certificado": "View certificate",
  "Ver como desbloquear": "See how to unlock",
  "Ver como ter acesso": "See how to get access",
  "Ver no mapa": "View on map",
  "Ver o que está disponível": "See what's available",
  "Ver o que há na Vitrine": "See what's in the Showcase",
  "Ver página": "View page",
  "Ver todas as conquistas": "See all achievements",
  "Ver todos": "See all",
  "Verifique a ligação à internet e recarregue a página.": "Check your internet connection and reload the page.",
  "Vitrine": "Showcase",
  "Voltar": "Back",
  "Voltar a Meus cursos": "Back to My courses",
  "Voltar ao curso": "Back to the course",
  "WhatsApp": "WhatsApp",
  "{certas} de {total} certas.": "{certas} of {total} correct.",
  "{data}, às {hora}": "{data}, at {hora}",
  "{dia} às {hora}": "{dia} at {hora}",
  "{feitas} de {total} aulas": "{feitas} of {total} lessons",
  "{feitas} de {total} aulas concluídas": "{feitas} of {total} lessons completed",
  "{feitas}/{total} aulas": "{feitas}/{total} lessons",
  "{feito}/{meta} para o nível {n}": "{feito}/{meta} to level {n}",
  "{nota} de 5": "{nota} out of 5",
  "{n} aulas": "{n} lessons",
  "{n} avaliações": "{n} ratings",
  "{n} conteúdos": "{n} items",
  "{n} cursos": "{n} courses",
  "{n} dias seguidos": "{n} days in a row",
  "{n} módulos": "{n} modules",
  "{pct}% concluído": "{pct}% complete",
  "{pct}% de {regra}% — continue para desbloquear": "{pct}% of {regra}% — keep going to unlock",
  "{pct}% do curso": "{pct}% of the course",
  "{xp} XP acumulados": "{xp} XP earned",
  "Área": "Area",
  "Área de Membros": "Members Area",
  "Não foi possível enviar o ficheiro. Recarregue a página e tente de novo.": "The file could not be uploaded. Reload the page and try again.",
};
